server/webapp/WEB-INF/rails/config/routes.rb
  post "admin/:stage_parent/:pipeline_name/stages/:stage_name/index/decrement" => "admin/stages#decrement_index", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_parent: /(pipelines|templates)/, stage_name: STAGE_NAME_FORMAT}, as: :admin_stage_decrement_index
  get "admin/:stage_parent/:pipeline_name/stages/:stage_name/:current_tab" => "admin/stages#edit", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_parent: /(pipelines|templates)/, current_tab: /(settings|environment_variables|permissions)/, stage_name: STAGE_NAME_FORMAT}, as: :admin_stage_edit
  put "admin/:stage_parent/:pipeline_name/stages/:stage_name/:current_tab" => "admin/stages#update", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_parent: /(pipelines|templates)/, current_tab: /(settings|environment_variables|permissions)/, stage_name: STAGE_NAME_FORMAT}, as: :admin_stage_update
  get "admin/config_change/between/:later_md5/and/:earlier_md5" => 'admin/stages#config_change', as: :admin_config_change

  get "admin/:stage_parent/:pipeline_name/stages/:stage_name/jobs" => "admin/jobs#index", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_name: STAGE_NAME_FORMAT, stage_parent: /(pipelines|templates)/}, as: :admin_job_listing
  get "admin/:stage_parent/:pipeline_name/stages/:stage_name/jobs/new" => "admin/jobs#new", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_name: STAGE_NAME_FORMAT, stage_parent: /(pipelines|templates)/}, as: :admin_job_new
  post "admin/:stage_parent/:pipeline_name/stages/:stage_name/jobs" => "admin/jobs#create", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_name: STAGE_NAME_FORMAT, stage_parent: /(pipelines|templates)/}, as: :admin_job_create
  put "admin/:stage_parent/:pipeline_name/stages/:stage_name/job/:job_name/:current_tab" => "admin/jobs#update", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_name: STAGE_NAME_FORMAT, stage_parent: /(pipelines|templates)/, job_name: JOB_NAME_FORMAT}, as: :admin_job_update #TODO: use job name format, so part splitting doesn't mess us up -JJ
  delete "admin/:stage_parent/:pipeline_name/stages/:stage_name/job/:job_name" => "admin/jobs#destroy", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_name: STAGE_NAME_FORMAT, stage_parent: /(pipelines|templates)/, job_name: JOB_NAME_FORMAT}, as: :admin_job_delete
  get "admin/:stage_parent/:pipeline_name/stages/:stage_name/job/:job_name/:current_tab" => "admin/jobs#edit", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_name: STAGE_NAME_FORMAT, stage_parent: /(pipelines|templates)/, current_tab: /#{["settings", "environment_variables", "artifacts", "resources", "tabs"].join("|")}/, job_name: JOB_NAME_FORMAT}, as: :admin_job_edit
  #put "admin/:stage_parent/:pipeline_name/stages/:stage_name/job/:job_name/:current_tab" => "admin/jobs#update", constraints: {pipeline_name: PIPELINE_NAME_FORMAT,  stage_name: STAGE_NAME_FORMAT, stage_parent: /(pipelines|templates)/, current_tab: /#{["settings", "environment_variables", "artifacts", "resources", "tabs"].join("|")}/, job_name: JOB_NAME_FORMAT}, as: :admin_job_update

  get "admin/commands" => "admin/commands#index", as: :admin_commands
  get "admin/commands/show" => "admin/commands#show", as: :admin_command_definition
  get "admin/commands/lookup" => "admin/commands#lookup", :format => "text", as: :admin_command_lookup

  get "admin/:stage_parent/:pipeline_name/stages/:stage_name/job/:job_name/tasks" => "admin/tasks#index", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_name: STAGE_NAME_FORMAT, job_name: JOB_NAME_FORMAT, stage_parent: /(pipelines|templates)/}, :current_tab => "tasks", as: :admin_tasks_listing
  get "admin/:stage_parent/:pipeline_name/stages/:stage_name/job/:job_name/tasks/:type/new" => "admin/tasks#new", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_name: STAGE_NAME_FORMAT, job_name: JOB_NAME_FORMAT, stage_parent: /(pipelines|templates)/}, :current_tab => "tasks", as: :admin_task_new
  post "admin/:stage_parent/:pipeline_name/stages/:stage_name/job/:job_name/tasks/:type" => "admin/tasks#create", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_name: STAGE_NAME_FORMAT, job_name: JOB_NAME_FORMAT, stage_parent: /(pipelines|templates)/}, :current_tab => "tasks", as: :admin_task_create
  post "admin/:stage_parent/:pipeline_name/stages/:stage_name/job/:job_name/task/:task_index/index/increment" => "admin/tasks#increment_index", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_name: STAGE_NAME_FORMAT, job_name: JOB_NAME_FORMAT, stage_parent: /(pipelines|templates)/}, :current_tab => "tasks", as: :admin_task_increment_index
  post "admin/:stage_parent/:pipeline_name/stages/:stage_name/job/:job_name/task/:task_index/index/decrement" => "admin/tasks#decrement_index", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_name: STAGE_NAME_FORMAT, job_name: JOB_NAME_FORMAT, stage_parent: /(pipelines|templates)/}, :current_tab => "tasks", as: :admin_task_decrement_index
  get "admin/:stage_parent/:pipeline_name/stages/:stage_name/job/:job_name/tasks/:type/:task_index/edit" => "admin/tasks#edit", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_name: STAGE_NAME_FORMAT, job_name: JOB_NAME_FORMAT, task_index: NON_NEGATIVE_INTEGER, stage_parent: /(pipelines|templates)/}, :current_tab => "tasks", as: :admin_task_edit
  delete "admin/:stage_parent/:pipeline_name/stages/:stage_name/job/:job_name/tasks/:task_index" => "admin/tasks#destroy", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_name: STAGE_NAME_FORMAT, job_name: JOB_NAME_FORMAT, task_index: NON_NEGATIVE_INTEGER, stage_parent: /(pipelines|templates)/}, :current_tab => "tasks", as: :admin_task_delete
  put "admin/:stage_parent/:pipeline_name/stages/:stage_name/job/:job_name/tasks/:type/:task_index" => "admin/tasks#update", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_name: STAGE_NAME_FORMAT, job_name: JOB_NAME_FORMAT, task_index: NON_NEGATIVE_INTEGER, stage_parent: /(pipelines|templates)/}, :current_tab => "tasks", as: :admin_task_update

  get "admin/config_xml" => "admin/configuration#show", as: :config_view
  put "admin/config_xml" => "admin/configuration#update", as: :config_update
  get "admin/config_xml/edit" => "admin/configuration#edit", as: :config_edit

  get "admin/config/server" => "admin/server#index", as: :edit_server_config
  post "admin/config/server/update" => "admin/server#update", as: :update_server_config
  post "admin/config/server/validate" => "admin/server#validate", as: :validate_server_config_params, constraints: HeaderConstraint.new
  post "admin/config/server/test_email" => "admin/server#test_email", as: :send_test_email

  get "admin/pipelines" => "admin/pipeline_groups#index", as: :pipeline_groups
  get "admin/pipeline_group/new" => "admin/pipeline_groups#new", as: :pipeline_group_new
  post "admin/pipeline_group" => "admin/pipeline_groups#create", as: :pipeline_group_create
  put "admin/pipelines/move/:pipeline_name" => "admin/pipeline_groups#move", constraints: {pipeline_name: PIPELINE_NAME_FORMAT}, as: :move_pipeline_to_group
  delete "admin/pipelines/:pipeline_name" => "admin/pipeline_groups#destroy", constraints: {pipeline_name: PIPELINE_NAME_FORMAT}, as: :delete_pipeline
  get "admin/pipeline_group/:group_name/edit" => "admin/pipeline_groups#edit", constraints: {group_name: GROUP_NAME_FORMAT}, as: :pipeline_group_edit
  get "admin/pipeline_group/:group_name" => "admin/pipeline_groups#show", constraints: {group_name: GROUP_NAME_FORMAT}, as: :pipeline_group_show
  put "admin/pipeline_group/:group_name" => "admin/pipeline_groups#update", constraints: {group_name: GROUP_NAME_FORMAT}, as: :pipeline_group_update
  delete "admin/pipeline_group/:group_name" => "admin/pipeline_groups#destroy_group", constraints: {group_name: GROUP_NAME_FORMAT}, as: :pipeline_group_delete
  get "/admin/pipelines/possible_groups/:pipeline_name/:config_md5" => "admin/pipeline_groups#possible_groups", constraints: {pipeline_name: PIPELINE_NAME_FORMAT}, as: :possible_groups

  get "admin/templates" => "admin/templates#index", as: :templates
  get "admin/templates/new" => "admin/templates#new", as: :template_new
  post "admin/templates/create" => "admin/templates#create", as: :template_create
  delete "admin/templates/:pipeline_name" => "admin/templates#destroy", constraints: {pipeline_name: PIPELINE_NAME_FORMAT}, as: :delete_template
  get "admin/templates/:template_name/permissions" => "admin/templates#edit_permissions", constraints: {template_name: TEMPLATE_NAME_FORMAT}, as: :edit_template_permissions
  post "admin/templates/:template_name/permissions" => "admin/templates#update_permissions", constraints: {template_name: TEMPLATE_NAME_FORMAT}, as: :update_template_permissions
  get "admin/:stage_parent/:pipeline_name/:current_tab" => "admin/templates#edit", constraints: {stage_parent: "templates", pipeline_name: PIPELINE_NAME_FORMAT, current_tab: /#{["general"].join("|")}/}, defaults: {stage_parent: "templates"}, as: :template_edit
  put "admin/:stage_parent/:pipeline_name/:current_tab" => "admin/templates#update", constraints: {stage_parent: "templates", pipeline_name: PIPELINE_NAME_FORMAT, current_tab: /#{["general"].join("|")}/}, defaults: {stage_parent: "templates"}, as: :template_update

  get "admin/package_definitions/:repo_id/new" => "admin/package_definitions#new", as: :package_definitions_new
  get "admin/package_definitions/:repo_id/new_for_new_pipeline_wizard" => "admin/package_definitions#new_for_new_pipeline_wizard", as: :package_definitions_new_for_new_pipeline_wizard
  get "admin/package_definitions/:repo_id/:package_id/pipelines_used_in" => "admin/package_definitions#pipelines_used_in", as: :pipelines_used_in
  get "admin/package_definitions/:repo_id/:package_id" => "admin/package_definitions#show", as: :package_definitions_show

server/webapp/WEB-INF/rails/app/helpers/admin/task_helper.rb
#
# Copyright 2019 ThoughtWorks, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

module Admin
  module TaskHelper
    include JavaImports

    def task_options
      available_models = task_view_service.getTaskViewModels().select do |tvm| !(is_fetch_task?(tvm.getTaskType()) || is_exec_task?(tvm.getTaskType())) end

      result = available_models.collect do |tvm| [tvm.getTypeForDisplay(), tvm.getTaskType()] end
      result << ["More...", ExecTask.new.getTaskType()]
    end

    def selected_option oncancel_config
      oncancel_config.getTask().getTaskType()
    end

    def task_css_class task_type
      return 'lookup_icon' if is_exec_task? task_type
      ''
    end

    def is_fetch_task? task_type
      task_type == "fetch"
    end

    def is_exec_task? task_type
      task_type == ExecTask.new.getTaskType()
    end
  end
end

server/webapp/WEB-INF/rails/app/views/admin/tasks/_on_cancel.html.erb
<div class="on_cancel fieldset">
    <%
       task = scope[:task]
    %>
    <%- if (task.hasCancelTask() && (task.cancelTask().instance_of? com.thoughtworks.go.config.pluggabletask.PluggableTask) && !scope[:config_store].preferenceFor(task.cancelTask().getPluginConfiguration().getId())) %>
        <div class="flash" id="plugin_missing_error">
            <p class="warning">On Cancel task is not available because associated plugin '<%= task.cancelTask().getPluginConfiguration().getId() %>' is missing. Please contact Go admin to verify or re-install plugin. Click on 'Save' will replace the current On Cancel task.</p>
        </div>
    <%- end %>

    <%= scope[:form].check_box(com.thoughtworks.go.config.AbstractTask::HAS_CANCEL_TASK, :class => "has_cancel_task", :id => "has_cancel_task") -%>
    <%= label_tag :has_cancel_task, 'On Cancel Task', :class => "inline" -%>
    <div class="on_cancel_task <%= task.hasCancelTask() ? '' : 'hidden' %>">
        <%= scope[:form].fields_for com.thoughtworks.go.config.AbstractTask::ON_CANCEL_CONFIG, task.onCancelConfig do |on_cancel_config| %>
            <%= on_cancel_config.select(com.thoughtworks.go.config.OnCancelConfig::ON_CANCEL_OPTIONS, task_options, {:selected => selected_option(task.onCancelConfig())}, {:class => "on_cancel_type", :id => "on_cancel_task_options"}) %>
            <% tasks = com.thoughtworks.go.config.Tasks.new() %>
            <% @on_cancel_task_vms.each do |oncancel_task_vm|
                oncancel_task = oncancel_task_vm.getModel()
                task_class_name = oncancel_task.getTaskType()
                next if task_class_name == "fetch"
            %>
                <div class="hidden task_entry <%= task_class_name -%>">
                    <%= on_cancel_config.fields_for oncancel_task.getTaskType() + "OnCancel", oncancel_task do |task_form| %>
                        <%== render_pluggable_form_template(oncancel_task_vm, form_name_provider(task_form), {:scope => {:form => task_form, :task => oncancel_task}}) -%>
                    <% end %>
                </div>
            <% end %>
        <% end %>
    </div>
</div>

<script type="text/javascript">
    Util.on_load(function() {
        var helper = new TaskEditor.TypeEditor({container: jQuery('.on_cancel_task'), switch_control: jQuery('.on_cancel_type'), entry_to_be_hidden: '.task_entry'});
        helper.showHideCheckbox(jQuery('.has_cancel_task'));//memory leak
    });
</script>

server/webapp/WEB-INF/rails/app/views/admin/tasks/_runif.html.erb
<div class="form_item_block <%= scope[:on_cancel] ? "on_cancel_" : "" -%>run_if_options" id="<%= scope[:runif_container] = random_dom_id('run_if_options_') -%>">
    <label><%== required_label_text('Run If Conditions') -%></label>

    <%= scope[:form].check_box com.thoughtworks.go.config.AbstractTask::RUN_IF_CONFIGS_PASSED, {:class => "runif passed", :include_hidden => false, :id => scope[:run_if] = random_dom_id("runif_passed_")} %>
    <%= label_tag scope[:run_if], h('Passed'), :class => "condition" -%>

    <%= scope[:form].check_box com.thoughtworks.go.config.AbstractTask::RUN_IF_CONFIGS_FAILED, {:class => "runif failed", :include_hidden => false, :id => scope[:run_if] = random_dom_id("runif_failed_")} %>
    <%= label_tag scope[:run_if], h('Failed'), :class => "condition" -%>

    <%= scope[:form].check_box com.thoughtworks.go.config.AbstractTask::RUN_IF_CONFIGS_ANY, {:class => "runif any", :include_hidden => false, :id => scope[:run_if] = random_dom_id("runif_any_")} %>
    <%= label_tag scope[:run_if], h('Any'), :class => "condition" -%>

    <script type="text/javascript">
        Util.on_load(function() {
            new TaskEditor.RunIfEditor(jQuery("#<%= scope[:runif_container] -%>"));
        });
    </script>
</div>

server/webapp/WEB-INF/rails/app/views/admin/tasks/index.html.erb
<div class="config-container config-tasks">
  <h3>Tasks</h3>
  <table class="list_table reorderable_table tasks_list_table">
    <thead>
    <tr>
      <th>Order</th>
      <th>Task Type</th>
      <th class="run_ifs">Run If Conditions</th>
      <th>Properties</th>
      <th>On Cancel</th>
      <th class="">Remove</th>
    </tr>
    </thead>
    <tbody>
    <% @tasks.each_with_index do |task_for_listing, task_config_index| %>
      <%- tvm_of_task_listing = task_view_service.getViewModel(task_for_listing, 'list-entry') -%>
      <%- tvm_of_cancel_task_or_nil = task_for_listing.hasCancelTask() ? task_view_service.getViewModel(task_for_listing.cancelTask(), 'list-entry') : nil -%>
      <%= render :partial => "/admin/tasks/plugin/task_entry.html", :locals => {:scope => {:tvm => tvm_of_task_listing, :tvm_of_cancel_task => tvm_of_cancel_task_or_nil,
                                                                                           :task_config_index => task_config_index, :task_config => tvm_of_task_listing.getModel()}} -%>
    <% end %>
    <tr>
      <td>&nbsp;</td>
      <td colspan="5">
        <%= action_icon({:type => "add", :text => 'Add new task', :id => "add_new_task_dropdown_link", :href => "#", :menu_link => true}) %>
        <div id="new_task_popup" class="hidden enhanced_dropdown">
          <ul>
            <% @task_view_models.each do |tvm_of_task_listing| %>
              <% if is_exec_task? tvm_of_task_listing.getTaskType()
                   @tvm_of_custom_command = tvm_of_task_listing
              %>
              <% elsif tvm_of_task_listing.getTypeForDisplay() != com.thoughtworks.go.config.FetchPluggableArtifactTask::FETCH_EXTERNAL_ARTIFACT %>
                <li>
                  <%= link_to tvm_of_task_listing.getTypeForDisplay(), '#',
                              :onclick => "Modalbox.show('#{admin_task_new_path(:type => tvm_of_task_listing.getTaskType())}', {overlayClose: false, title: '#{'Add new task'} - #{tvm_of_task_listing.getTypeForDisplay}'})",
                              :class => task_css_class(tvm_of_task_listing.getTaskType()) -%>
                </li>
              <% end %>
            <% end %>
            <li class="menu_item_last_with_border">
              <%= link_to "More...", '#',
                          :onclick => "ModalBoxWhichClosesAutoCompleteDropDownBeforeClosing.show('#{admin_task_new_path(:type => @tvm_of_custom_command.getTaskType())}', {overlayClose: false, title: '#{'Add new task'} - #{@tvm_of_custom_command.getTypeForDisplay()}'})",
                          :class => task_css_class(@tvm_of_custom_command.getTaskType()) -%>
            </li>

          </ul>
        </div>
      </td>
    </tr>
    </tbody>
  </table>
</div>
<script type="text/javascript">
  AjaxForm.error_box_selector = '#MB_content';
  Util.on_load(function () {
    var newTaskPopup       = new MicroContentPopup(jQuery('#new_task_popup').get(0), new MicroContentPopup.NoOpHandler());
    var newTaskPopupShower = new MicroContentPopup.ClickShower(newTaskPopup);
    newTaskPopupShower.bindShowButton(jQuery('#add_new_task_dropdown_link').get(0));
  });
</script>