server/webapp/WEB-INF/rails/config/routes.rb
#
# Copyright 2019 ThoughtWorks, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

Rails.application.routes.draw do
  unless defined?(CONSTANTS)
    CONFIG_REPO_ID_FORMAT = ROLE_NAME_FORMAT = USER_NAME_FORMAT = GROUP_NAME_FORMAT = TEMPLATE_NAME_FORMAT = PIPELINE_NAME_FORMAT = STAGE_NAME_FORMAT = ENVIRONMENT_NAME_FORMAT = /[\w\-][\w\-.]*/
    JOB_NAME_FORMAT = /[\w\-.]+/
    PIPELINE_COUNTER_FORMAT = STAGE_COUNTER_FORMAT = /-?\d+/
    NON_NEGATIVE_INTEGER = /\d+/
    PIPELINE_LOCATOR_CONSTRAINTS = {:pipeline_name => PIPELINE_NAME_FORMAT, :pipeline_counter => PIPELINE_COUNTER_FORMAT}
    STAGE_LOCATOR_CONSTRAINTS = {:stage_name => STAGE_NAME_FORMAT, :stage_counter => STAGE_COUNTER_FORMAT}.merge(PIPELINE_LOCATOR_CONSTRAINTS)
    ENVIRONMENT_NAME_CONSTRAINT = {:name => ENVIRONMENT_NAME_FORMAT}
    MERGED_ENVIRONMENT_NAME_CONSTRAINT = {:environment_name => ENVIRONMENT_NAME_FORMAT}
    PLUGIN_ID_FORMAT = /[\w\-.]+/
    ALLOW_DOTS = /[^\/]+/
    CONSTANTS = true
  end

  # This is used to generate _url and _path in application_helper#url_for_path
  get '/', to: redirect('/go/pipelines'), as: :root

  get "admin/pipelines/snippet" => "admin/pipelines_snippet#index", as: :pipelines_snippet
  get "admin/pipelines/snippet/:group_name" => "admin/pipelines_snippet#show", constraints: {group_name: GROUP_NAME_FORMAT}, as: :pipelines_snippet_show
  get "admin/pipelines/snippet/:group_name/edit" => "admin/pipelines_snippet#edit", constraints: {group_name: GROUP_NAME_FORMAT}, as: :pipelines_snippet_edit
  put "admin/pipelines/snippet/:group_name" => "admin/pipelines_snippet#update", constraints: {group_name: GROUP_NAME_FORMAT}, as: :pipelines_snippet_update

  ["svn", "git", "hg", "p4", "dependency", "tfs", "package"].each do |material_type|
    get "admin/pipelines/:pipeline_name/materials/#{material_type}/new" => "admin/materials/#{material_type}#new", constraints: {pipeline_name: PIPELINE_NAME_FORMAT}, as: "admin_#{material_type}_new"
    post "admin/pipelines/:pipeline_name/materials/#{material_type}" => "admin/materials/#{material_type}#create", constraints: {pipeline_name: PIPELINE_NAME_FORMAT}, as: "admin_#{material_type}_create"
    get "admin/pipelines/:pipeline_name/materials/#{material_type}/:finger_print/edit" => "admin/materials/#{material_type}#edit", constraints: {pipeline_name: PIPELINE_NAME_FORMAT}, as: "admin_#{material_type}_edit"
    put "admin/pipelines/:pipeline_name/materials/#{material_type}/:finger_print" => "admin/materials/#{material_type}#update", constraints: {pipeline_name: PIPELINE_NAME_FORMAT}, as: "admin_#{material_type}_update"
  end
  defaults :no_layout => true do
    get "admin/pipelines/:pipeline_name/materials/dependency/pipeline_name_search" => "admin/materials/dependency#pipeline_name_search", constraints: {pipeline_name: PIPELINE_NAME_FORMAT}, as: :admin_dependency_material_pipeline_name_search
    get "admin/pipelines/:pipeline_name/materials/dependency/load_stage_names_for" => "admin/materials/dependency#load_stage_names_for", constraints: {pipeline_name: PIPELINE_NAME_FORMAT}, as: :admin_dependency_material_load_stage_names_for
  end
  get "admin/:stage_parent/:pipeline_name/materials" => "admin/materials#index", constraints: {stage_parent: "pipelines", pipeline_name: PIPELINE_NAME_FORMAT}, defaults: {stage_parent: "pipelines"}, as: :admin_material_index
  delete "admin/:stage_parent/:pipeline_name/materials/:finger_print" => "admin/materials#destroy", constraints: {stage_parent: "pipelines", pipeline_name: PIPELINE_NAME_FORMAT}, defaults: {stage_parent: "pipelines"}, as: :admin_material_delete

  get "admin/pipeline/new" => "admin/pipelines#new", as: :pipeline_new
  get "admin/pipelines/create" => "admin/pipelines#new", as: :new_pipeline_new
  post "admin/pipelines" => "admin/pipelines#create", as: :pipeline_create
  get "admin/pipeline/:pipeline_name/clone" => "admin/pipelines#clone", constraints: {pipeline_name: PIPELINE_NAME_FORMAT}, as: :pipeline_clone
  post "admin/pipeline/save_clone" => "admin/pipelines#save_clone", as: :pipeline_save_clone
  get "admin/pipelines/:pipeline_name/pause_info.json" => "admin/pipelines#pause_info", :format => "json", constraints: {pipeline_name: PIPELINE_NAME_FORMAT}, as: :pause_info_refresh
  get "admin/:stage_parent/:pipeline_name/:current_tab" => "admin/pipelines#edit", constraints: {stage_parent: "pipelines", pipeline_name: PIPELINE_NAME_FORMAT, current_tab: /#{["general", "project_management", "environment_variables", "permissions", "parameters"].join("|")}/}, defaults: {stage_parent: "pipelines"}, as: :pipeline_edit
  put "admin/:stage_parent/:pipeline_name/:current_tab" => "admin/pipelines#update", constraints: {stage_parent: "pipelines", pipeline_name: PIPELINE_NAME_FORMAT, current_tab: /#{["general", "project_management", "environment_variables", "permissions", "parameters"].join("|")}/}, defaults: {stage_parent: "pipelines"}, as: :pipeline_update

  get "admin/:stage_parent/:pipeline_name/stages" => "admin/stages#index", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_parent: /(pipelines|templates)/}, as: :admin_stage_listing
  put "admin/:stage_parent/:pipeline_name/stages" => "admin/stages#use_template", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_parent: /(pipelines|templates)/}, as: :admin_stage_use_template
  get "admin/:stage_parent/:pipeline_name/stages/new" => "admin/stages#new", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_parent: /(pipelines|templates)/}, as: :admin_stage_new
  delete "admin/:stage_parent/:pipeline_name/stages/:stage_name" => "admin/stages#destroy", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_parent: /(pipelines|templates)/, stage_name: STAGE_NAME_FORMAT}, as: :admin_stage_delete
  post "admin/:stage_parent/:pipeline_name/stages" => "admin/stages#create", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_parent: /(pipelines|templates)/}, as: :admin_stage_create
  post "admin/:stage_parent/:pipeline_name/stages/:stage_name/index/increment" => "admin/stages#increment_index", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_parent: /(pipelines|templates)/, stage_name: STAGE_NAME_FORMAT}, as: :admin_stage_increment_index
  post "admin/:stage_parent/:pipeline_name/stages/:stage_name/index/decrement" => "admin/stages#decrement_index", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_parent: /(pipelines|templates)/, stage_name: STAGE_NAME_FORMAT}, as: :admin_stage_decrement_index
  get "admin/:stage_parent/:pipeline_name/stages/:stage_name/:current_tab" => "admin/stages#edit", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_parent: /(pipelines|templates)/, current_tab: /(settings|environment_variables|permissions)/, stage_name: STAGE_NAME_FORMAT}, as: :admin_stage_edit
  put "admin/:stage_parent/:pipeline_name/stages/:stage_name/:current_tab" => "admin/stages#update", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_parent: /(pipelines|templates)/, current_tab: /(settings|environment_variables|permissions)/, stage_name: STAGE_NAME_FORMAT}, as: :admin_stage_update
  get "admin/config_change/between/:later_md5/and/:earlier_md5" => 'admin/stages#config_change', as: :admin_config_change

  get "admin/:stage_parent/:pipeline_name/stages/:stage_name/jobs" => "admin/jobs#index", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_name: STAGE_NAME_FORMAT, stage_parent: /(pipelines|templates)/}, as: :admin_job_listing
  get "admin/:stage_parent/:pipeline_name/stages/:stage_name/jobs/new" => "admin/jobs#new", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_name: STAGE_NAME_FORMAT, stage_parent: /(pipelines|templates)/}, as: :admin_job_new
  post "admin/:stage_parent/:pipeline_name/stages/:stage_name/jobs" => "admin/jobs#create", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_name: STAGE_NAME_FORMAT, stage_parent: /(pipelines|templates)/}, as: :admin_job_create
  put "admin/:stage_parent/:pipeline_name/stages/:stage_name/job/:job_name/:current_tab" => "admin/jobs#update", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_name: STAGE_NAME_FORMAT, stage_parent: /(pipelines|templates)/, job_name: JOB_NAME_FORMAT}, as: :admin_job_update #TODO: use job name format, so part splitting doesn't mess us up -JJ
  delete "admin/:stage_parent/:pipeline_name/stages/:stage_name/job/:job_name" => "admin/jobs#destroy", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_name: STAGE_NAME_FORMAT, stage_parent: /(pipelines|templates)/, job_name: JOB_NAME_FORMAT}, as: :admin_job_delete
  get "admin/:stage_parent/:pipeline_name/stages/:stage_name/job/:job_name/:current_tab" => "admin/jobs#edit", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_name: STAGE_NAME_FORMAT, stage_parent: /(pipelines|templates)/, current_tab: /#{["settings", "environment_variables", "artifacts", "resources", "tabs"].join("|")}/, job_name: JOB_NAME_FORMAT}, as: :admin_job_edit
  #put "admin/:stage_parent/:pipeline_name/stages/:stage_name/job/:job_name/:current_tab" => "admin/jobs#update", constraints: {pipeline_name: PIPELINE_NAME_FORMAT,  stage_name: STAGE_NAME_FORMAT, stage_parent: /(pipelines|templates)/, current_tab: /#{["settings", "environment_variables", "artifacts", "resources", "tabs"].join("|")}/, job_name: JOB_NAME_FORMAT}, as: :admin_job_update

  get "admin/commands" => "admin/commands#index", as: :admin_commands
  get "admin/commands/show" => "admin/commands#show", as: :admin_command_definition

server/webapp/WEB-INF/rails/app/helpers/admin/pipelines_helper.rb
#
# Copyright 2019 ThoughtWorks, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

module Admin
  module PipelinesHelper
    include JavaImports

    def default_stage_config
      job_configs = JobConfigs.new([JobConfig.new(CaseInsensitiveString.new("defaultJob"), ResourceConfigs.new, ArtifactConfigs.new, com.thoughtworks.go.config.Tasks.new([AntTask.new].to_java(Task)))].to_java(JobConfig))
      StageConfig.new(CaseInsensitiveString.new("defaultStage"), job_configs)
    end
  end
end

server/webapp/WEB-INF/rails/app/helpers/api/pipelines_helper.rb
#
# Copyright 2019 ThoughtWorks, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

module Api
  module PipelinesHelper
    include JavaImports

    def url(params={})#FIXME: we should not have such common method names(we work with all helpers mixed in each response, which means we need to be have more specific method names to avoid conflicts)
      api_pipeline_stage_feed_url(params)
    end

    def resource_url(params={})#FIXME: we should not have such common method names(we work with all helpers mixed in each response, which means we need to be have more specific method names to avoid conflicts)
      stage_url(params)
    end

    def page_url(stage_locator, options = {})#FIXME: we should not have such common method names(we work with all helpers mixed in each response, which means we need to be have more specific method names to avoid conflicts)
      stage_identifier = StageIdentifier.new(stage_locator)
      stage_detail_tab_default_url({:pipeline_name => stage_identifier.getPipelineName(),
                        :pipeline_counter => stage_identifier.getPipelineCounter().to_s,
                        :stage_name => stage_identifier.getStageName(),
                        :stage_counter => stage_identifier.getStageCounter()}.merge(options))
    end

  end
end

server/webapp/WEB-INF/rails/app/helpers/pipelines_helper.rb
#
# Copyright 2019 ThoughtWorks, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

module PipelinesHelper
  include JavaImports
  include StagesHelper
  include ERB::Util

  def stage_bar_url stage, action
    stage_id = stage.getIdentifier()
    stage.isScheduled() ? stage_detail_tab_path_for(:stage_name => stage_id.getStageName(), :stage_counter => stage_id.getStageCounter(), :pipeline_name => stage_id.getPipelineName(), :pipeline_counter => stage_id.getPipelineCounter(), :action => action) : "#"
  end

  def run_stage_label stage
    (stage.isScheduled() ? "rerun" : "trigger")
  end

  def trigger_message(actual_date_time, pim)
    if pim.class != com.thoughtworks.go.presentation.pipelinehistory.PreparingToScheduleInstance
      "Triggered&nbsp;#{'by'}&nbsp;<span class='who'>#{h pim.getApprovedBy()}</span>"
    else
      ""
    end
  end

  def trigger_message_with_formatted_date_time(date_time, who)
    on = "&nbsp;on&nbsp;<span class='time' data='#{date_time.getTime()}' title='#{date_time.to_long_display_date_time} server time'></span>"
    if who == GoConstants::DEFAULT_APPROVED_BY
      "<span class='label'>Automatically triggered</span>#{on}".html_safe
    else
      "<span class='label'>Triggered</span>&nbsp;by&nbsp;<span class='who'>#{h who}</span>#{on}".html_safe
    end
  end

  def pipelines_pipeline_dom_id(pipeline_model)
    "pipeline_#{pipeline_name(pipeline_model)}_panel"
  end

  def pipelines_dom_id(pipeline_group_name)
    "pipeline_group_#{pipeline_group_name}_panel"
  end

  def pipeline_name pipeline_model
    pipeline_model.getLatestPipelineInstance().getName()
  end

  def material_type(material)
    dependency?(material) ? 'dependency' : 'scm'
  end

  def dependency?(material)
    material.is_a? DependencyMaterial
  end

  def revision_for(revision)
    if dependency?(revision.getMaterial())
      "#{revision.getRevision().getPipelineName()}/#{revision.getRevision().getPipelineCounter()}"
    else
      revision.getLatestShortRevision()
    end
  end

  def pipeline_instance_identifier(pim)
    "#{pim.getName()}_#{pim.getCounter()}"
  end

  def pipeline_build_cause_popup_id(pim)
    "changes_#{pipeline_instance_identifier(pim)}"
  end

  def build_cause_popup_id_for_pipeline_counter(counter, prefix = nil)
    "#{prefix}for_pipeline_#{counter}"
  end

  def url_for_pipeline_value_stream_map(pipeline, options = {})
    vsm_show_path(options.merge({:pipeline_name => pipeline.getName(), :pipeline_counter => pipeline.getCounter(), :action => "show"}))
  end

  def url_for_dmr(dmr)
    "/go/pipelines/value_stream_map/#{dmr.getPipelineName()}/#{dmr.getPipelineCounter()}"
  end

  def with_pipeline_analytics_support(&block)
    return unless block_given?

    return if show_analytics_only_for_admins? && !is_user_an_admin?

    default_plugin_info_finder.allPluginInfos(PluginConstants.ANALYTICS_EXTENSION).each do |combined_plugin_info|
      extension_info = combined_plugin_info.extensionFor(PluginConstants.ANALYTICS_EXTENSION)
      if extension_info.getCapabilities().supportsPipelineAnalytics()
        supported_analytics = extension_info.getCapabilities().supportedPipelineAnalytics().get(0)
        yield combined_plugin_info.getDescriptor().id(), supported_analytics.getId()
        break
      end
    end
  end

  def show_analytics_only_for_admins?
    system_environment.enableAnalyticsOnlyForAdmins
  end
end

server/webapp/WEB-INF/rails/app/views/pipelines/_pipeline_header.html.erb
<% if @lockedPipeline
     scope[:entity_wrapper_class] = "locked"
   end %>

<div class="entity_status_wrapper page_header <%= scope[:entity_wrapper_class] %>">
  <div class="row">
    <span class="page_name">Stage Details</span>
    <%= render :partial => "shared/pipeline_breadcrumb.html", :locals => {:scope => {:pipeline => @pipeline, :third => {:link => url_for_pipeline_value_stream_map(@pipeline), :text => @pipeline.getLabel()}, :fourth => @stage.getName()}} %>

    <% if @can_user_view_settings %>
        <div class="stage_detail_setting">
          <%= link_to '', pipeline_edit_path(pipeline_name: @pipeline.getName(), current_tab: 'general'), class: 'icon16 setting' %>
        </div>
    <% end %>
    <% if @lockedPipeline %>
        <% if @pipeline.hasStage(@lockedPipeline) %>
            <% if @pipeline.canUnlock() %>
                <div class="locked_instance" id='unlock'>
                  <%== blocking_link_to_remote_new :name => "Click to unlock", :method => :post, :url => "/go/api/pipelines/#{@pipeline.getName()}/unlock",
                                                   :update => {:failure => "message_pane", :success => 'function(){}'}, :html => {}, :headers => {'X-GoCD-Confirm' => 'true', 'Accept' => 'application/vnd.go.cd.v1+json', 'Content-Type' => 'application/json'}, :before => "spinny('unlock');" %>
                </div>
            <% else %>
                <div class="locked_instance">
                  <span>LOCKED</span>
                </div>
            <% end %>
        <% else %>
            <div class="locked_instance">
              (<%= link_to("Locked by #{@lockedPipeline.getPipelineLabel()}" , stage_detail_path_for_identifier(@lockedPipeline)) %>
              )
            </div>
        <% end %>
    <% elsif @pipeline.isLockable() %>
        <div class="locked_instance">
          <span>UNLOCKED</span>
        </div>
    <% end %>
    <a href="<%= api_pipeline_stage_feed_path(:name => @pipeline.getName()) -%>">
      <div class="feed">&nbsp;</div>
    </a>
  </div>
</div>

server/webapp/WEB-INF/rails/app/views/pipelines/_pipeline_stage_bar.html.erb
<%- scope[:stage_details_action] ||= params[:action] -%>
<div id="stage_bar_<%= scope[:idx_in_status_bar] %>" class="row1">
    <% if placeholder_stage?(scope[:stage_in_status_bar]) %>
        <span class="stage_name"><%= scope[:stage_name] -%></span>
    <% else %>
        <%= link_to scope[:stage_in_status_bar].getName(), stage_bar_url(scope[:stage_in_status_bar], scope[:stage_details_action]), :class=> "stage_name" %>
    <% end %>

    <% if scope[:stage_in_status_bar].hasOperatePermission() %>
        <%

           if scope[:stage_in_status_bar].isRunning()
               scope[:label] = "cancel"
           elsif scope[:stage_in_status_bar].canRun()
               scope[:label] = run_stage_label(scope[:stage_in_status_bar])
           end

           scope[:operate_class] = "action_#{scope[:label]}"
        %>
        <div id="operate_<%= scope[:stage_name] %>" class="operate secondary <%= scope[:operate_class] %>">
            <%
               scope[:id] = "stage_bar_#{scope[:label]}_#{scope[:stage_name]}"
               scope[:title] = "#{scope[:label]} #{scope[:stage_name]}"
               scope[:html_opts] = {:class => "stage_action", :id => scope[:id] ,:title => scope[:title] ,:'aria-label' => scope[:title]}
               scope[:before_opts] = "spinny('operate_#{scope[:stage_name]}')"
               if scope[:stage_in_status_bar].canRun() && scope[:stage_in_status_bar].isScheduled() %>
                <%== blocking_link_to_remote_new :name => "&nbsp;", :method => :post, :url => run_stage_path(:stage_name => scope[:stage_name]), :html => scope[:html_opts], :update => scope[:update_opts], :headers => {Confirm: 'true'}, :before => scope[:before_opts] %>

        <% end %>
            <% if scope[:stage_in_status_bar].isRunning() %>
                <%== blocking_link_to_remote_new :name => "&nbsp;", :method => :post, :url => cancel_stage_path(:id => scope[:stage_in_status_bar].getId()), :html => scope[:html_opts], :update => scope[:update_opts], :headers => {Confirm: 'true'} , :before => scope[:before_opts] %>
            <% end %>
        </div>
    <% end %>
</div>
<% scope[:stage_bar_html_options] = stage_bar_options(scope[:stage_in_status_bar]) %>
<div class="stage_bar_wrapper">
    <% if placeholder_stage?(scope[:stage_in_status_bar]) %>
        <div <%= scope[:stage_bar_html_options] -%>></div>
    <% else %>
        <a href="<%= stage_bar_url(scope[:stage_in_status_bar], scope[:stage_details_action]) -%>" <%= scope[:stage_bar_html_options] -%>>
        <span><span></span></span></a>
    <% end %>
</div>
<% if scope[:idx_in_status_bar] > 0 %>
    <div class="trigger_gate">
        <%= render :partial => "pipelines/stage_trigger_gate.html", :locals => {:scope => {:stage_in_status_bar => scope[:stage_in_status_bar]}} %>
    </div>
<% end %>

server/webapp/WEB-INF/rails/app/views/pipelines/_stage_trigger_gate.html.erb
<%
title = if com.thoughtworks.go.util.GoConstants::DEFAULT_APPROVED_BY == scope[:stage_in_status_bar].getApprovedBy()
    "Automatically approved"
elsif scope[:stage_in_status_bar].getApprovedBy().blank?
    "Awaiting approval"
else
    "Approved by #{scope[:stage_in_status_bar].getApprovedBy()}"
end

clazz = scope[:stage_in_status_bar].isAutoApproved() ?
        "auto" :
        "manual"

stage_name = scope[:stage_in_status_bar].getName()
trigger_id = "stage_bar_trigger_" + stage_name
scope[:html_opts] = {:class => clazz, :title=> title, :id => trigger_id }
   
if scope[:stage_in_status_bar].canRun() && !scope[:stage_in_status_bar].isScheduled() %>
    <%== blocking_link_to_remote_new :name=>" ", :method => :post, :url => run_stage_path(:stage_name => stage_name), :html => scope[:html_opts], :update => scope[:update_opts], :headers => {Confirm: 'true'}, :before => scope[:before_opts] %>
<% else %>
    <span class="<%= clazz %>" title="<%= title %>" id="<%= trigger_id %>"> </span>
<% end %>

server/webapp/WEB-INF/rails/app/views/pipelines/_status_bar.html.erb
<% unless scope[:pipeline].nil?
   scope[:update_opts] = {:failure => "message_pane", :success => 'function(){}'}
%>
    <%- if is_config_used_to_run_this_stage_out_of_sync_with_current?(scope[:current_config_version], scope[:stage_config_version]) -%>
        <div class='config_changed_info notification'>
            <p class='information'>Configuration has since been updated and any operations performed will use the current configuration</p>
        </div>
    <%- end -%>
    <div class="pipeline">

        <ul class="stages">
            <%
               scope[:after_selected] = false
               scope[:pipeline].getStageHistory().each_with_index do |stage_in_status_bar, idx_in_status_bar|
                   scope[:selected] = params[:stage_name]==(scope[:stage_name]=stage_in_status_bar.getName())
                   scope[:stage_class] = "stage"
                   scope[:show_stage_actions_id] = id_for(stage_in_status_bar, "show_stage_actions")
                   if scope[:selected]
                       scope[:stage_class] += " selected"
                       scope[:after_selected] = true
                   elsif scope[:after_selected]
                       scope[:after_selected] = false
                       scope[:stage_class] += " after_selected"
                   end
            %>
                    <li style='<%= scope[:pipeline].numberOfStages() < 9 ? "width: " + stage_width_percent(scope[:pipeline].numberOfStages(), scope[:selected], 100) : "max-width: 300px" %>' class="<%= scope[:stage_class] %>">
                        <div class="wrapper">
                            <%= render :partial => "pipelines/pipeline_stage_bar.html", :locals => {:scope => {:idx_in_status_bar => idx_in_status_bar, :stage_in_status_bar => stage_in_status_bar, :stage_name => scope[:stage_name], :stage_details_action => scope[:stage_details_action]}} -%>
                        </div>
                    </li>
            <% end %>
        </ul>
    </div>
<% end %>

server/webapp/WEB-INF/rails/app/views/pipelines/build_cause.html.erb
<%= render(:partial => 'shared/build_cause_popup', :locals => {:scope => {:pipeline_instance => @pipeline_instance}}) %>