server/webapp/WEB-INF/rails/config/routes.rb
  #put "admin/:stage_parent/:pipeline_name/stages/:stage_name/job/:job_name/:current_tab" => "admin/jobs#update", constraints: {pipeline_name: PIPELINE_NAME_FORMAT,  stage_name: STAGE_NAME_FORMAT, stage_parent: /(pipelines|templates)/, current_tab: /#{["settings", "environment_variables", "artifacts", "resources", "tabs"].join("|")}/, job_name: JOB_NAME_FORMAT}, as: :admin_job_update

  get "admin/commands" => "admin/commands#index", as: :admin_commands
  get "admin/commands/show" => "admin/commands#show", as: :admin_command_definition
  get "admin/commands/lookup" => "admin/commands#lookup", :format => "text", as: :admin_command_lookup

  get "admin/:stage_parent/:pipeline_name/stages/:stage_name/job/:job_name/tasks" => "admin/tasks#index", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_name: STAGE_NAME_FORMAT, job_name: JOB_NAME_FORMAT, stage_parent: /(pipelines|templates)/}, :current_tab => "tasks", as: :admin_tasks_listing
  get "admin/:stage_parent/:pipeline_name/stages/:stage_name/job/:job_name/tasks/:type/new" => "admin/tasks#new", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_name: STAGE_NAME_FORMAT, job_name: JOB_NAME_FORMAT, stage_parent: /(pipelines|templates)/}, :current_tab => "tasks", as: :admin_task_new
  post "admin/:stage_parent/:pipeline_name/stages/:stage_name/job/:job_name/tasks/:type" => "admin/tasks#create", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_name: STAGE_NAME_FORMAT, job_name: JOB_NAME_FORMAT, stage_parent: /(pipelines|templates)/}, :current_tab => "tasks", as: :admin_task_create
  post "admin/:stage_parent/:pipeline_name/stages/:stage_name/job/:job_name/task/:task_index/index/increment" => "admin/tasks#increment_index", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_name: STAGE_NAME_FORMAT, job_name: JOB_NAME_FORMAT, stage_parent: /(pipelines|templates)/}, :current_tab => "tasks", as: :admin_task_increment_index
  post "admin/:stage_parent/:pipeline_name/stages/:stage_name/job/:job_name/task/:task_index/index/decrement" => "admin/tasks#decrement_index", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_name: STAGE_NAME_FORMAT, job_name: JOB_NAME_FORMAT, stage_parent: /(pipelines|templates)/}, :current_tab => "tasks", as: :admin_task_decrement_index
  get "admin/:stage_parent/:pipeline_name/stages/:stage_name/job/:job_name/tasks/:type/:task_index/edit" => "admin/tasks#edit", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_name: STAGE_NAME_FORMAT, job_name: JOB_NAME_FORMAT, task_index: NON_NEGATIVE_INTEGER, stage_parent: /(pipelines|templates)/}, :current_tab => "tasks", as: :admin_task_edit
  delete "admin/:stage_parent/:pipeline_name/stages/:stage_name/job/:job_name/tasks/:task_index" => "admin/tasks#destroy", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_name: STAGE_NAME_FORMAT, job_name: JOB_NAME_FORMAT, task_index: NON_NEGATIVE_INTEGER, stage_parent: /(pipelines|templates)/}, :current_tab => "tasks", as: :admin_task_delete
  put "admin/:stage_parent/:pipeline_name/stages/:stage_name/job/:job_name/tasks/:type/:task_index" => "admin/tasks#update", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, stage_name: STAGE_NAME_FORMAT, job_name: JOB_NAME_FORMAT, task_index: NON_NEGATIVE_INTEGER, stage_parent: /(pipelines|templates)/}, :current_tab => "tasks", as: :admin_task_update

  get "admin/config_xml" => "admin/configuration#show", as: :config_view
  put "admin/config_xml" => "admin/configuration#update", as: :config_update
  get "admin/config_xml/edit" => "admin/configuration#edit", as: :config_edit

  get "admin/config/server" => "admin/server#index", as: :edit_server_config
  post "admin/config/server/update" => "admin/server#update", as: :update_server_config
  post "admin/config/server/validate" => "admin/server#validate", as: :validate_server_config_params, constraints: HeaderConstraint.new
  post "admin/config/server/test_email" => "admin/server#test_email", as: :send_test_email

  get "admin/pipelines" => "admin/pipeline_groups#index", as: :pipeline_groups
  get "admin/pipeline_group/new" => "admin/pipeline_groups#new", as: :pipeline_group_new
  post "admin/pipeline_group" => "admin/pipeline_groups#create", as: :pipeline_group_create
  put "admin/pipelines/move/:pipeline_name" => "admin/pipeline_groups#move", constraints: {pipeline_name: PIPELINE_NAME_FORMAT}, as: :move_pipeline_to_group
  delete "admin/pipelines/:pipeline_name" => "admin/pipeline_groups#destroy", constraints: {pipeline_name: PIPELINE_NAME_FORMAT}, as: :delete_pipeline
  get "admin/pipeline_group/:group_name/edit" => "admin/pipeline_groups#edit", constraints: {group_name: GROUP_NAME_FORMAT}, as: :pipeline_group_edit
  get "admin/pipeline_group/:group_name" => "admin/pipeline_groups#show", constraints: {group_name: GROUP_NAME_FORMAT}, as: :pipeline_group_show
  put "admin/pipeline_group/:group_name" => "admin/pipeline_groups#update", constraints: {group_name: GROUP_NAME_FORMAT}, as: :pipeline_group_update
  delete "admin/pipeline_group/:group_name" => "admin/pipeline_groups#destroy_group", constraints: {group_name: GROUP_NAME_FORMAT}, as: :pipeline_group_delete
  get "/admin/pipelines/possible_groups/:pipeline_name/:config_md5" => "admin/pipeline_groups#possible_groups", constraints: {pipeline_name: PIPELINE_NAME_FORMAT}, as: :possible_groups

  get "admin/templates" => "admin/templates#index", as: :templates
  get "admin/templates/new" => "admin/templates#new", as: :template_new
  post "admin/templates/create" => "admin/templates#create", as: :template_create
  delete "admin/templates/:pipeline_name" => "admin/templates#destroy", constraints: {pipeline_name: PIPELINE_NAME_FORMAT}, as: :delete_template
  get "admin/templates/:template_name/permissions" => "admin/templates#edit_permissions", constraints: {template_name: TEMPLATE_NAME_FORMAT}, as: :edit_template_permissions
  post "admin/templates/:template_name/permissions" => "admin/templates#update_permissions", constraints: {template_name: TEMPLATE_NAME_FORMAT}, as: :update_template_permissions
  get "admin/:stage_parent/:pipeline_name/:current_tab" => "admin/templates#edit", constraints: {stage_parent: "templates", pipeline_name: PIPELINE_NAME_FORMAT, current_tab: /#{["general"].join("|")}/}, defaults: {stage_parent: "templates"}, as: :template_edit
  put "admin/:stage_parent/:pipeline_name/:current_tab" => "admin/templates#update", constraints: {stage_parent: "templates", pipeline_name: PIPELINE_NAME_FORMAT, current_tab: /#{["general"].join("|")}/}, defaults: {stage_parent: "templates"}, as: :template_update

  get "admin/package_definitions/:repo_id/new" => "admin/package_definitions#new", as: :package_definitions_new
  get "admin/package_definitions/:repo_id/new_for_new_pipeline_wizard" => "admin/package_definitions#new_for_new_pipeline_wizard", as: :package_definitions_new_for_new_pipeline_wizard
  get "admin/package_definitions/:repo_id/:package_id/pipelines_used_in" => "admin/package_definitions#pipelines_used_in", as: :pipelines_used_in
  get "admin/package_definitions/:repo_id/:package_id" => "admin/package_definitions#show", as: :package_definitions_show
  get "admin/package_definitions/:repo_id/:package_id/for_new_pipeline_wizard" => "admin/package_definitions#show_for_new_pipeline_wizard", as: :package_definitions_show_for_new_pipeline_wizard
  get "admin/package_definitions/:repo_id/:package_id/with_repository_list" => "admin/package_definitions#show_with_repository_list", as: :package_definitions_show_with_repository_list
  delete "admin/package_definitions/:repo_id/:package_id" => "admin/package_definitions#destroy", as: :package_definition_delete
  post "admin/package_definitions/check_connection" => "admin/package_definitions#check_connection", as: :package_definition_check_connection, constraints: HeaderConstraint.new

  get "admin/package_repositories/new" => "admin/package_repositories#new", as: :package_repositories_new
  post "admin/package_repositories/check_connection" => "admin/package_repositories#check_connection", as: :package_repositories_check_connection, constraints: HeaderConstraint.new
  get "admin/package_repositories/list" => "admin/package_repositories#list", as: :package_repositories_list
  get "admin/package_repositories/:id/edit" => "admin/package_repositories#edit", as: :package_repositories_edit
  post "admin/package_repositories" => "admin/package_repositories#create", as: :package_repositories_create
  put "admin/package_repositories/:id" => "admin/package_repositories#update", as: :package_repositories_update
  delete "admin/package_repositories/:id" => "admin/package_repositories#destroy", as: :package_repositories_delete
  get "admin/package_repositories/:plugin/config/" => "admin/package_repositories#plugin_config", constraints: {:plugin => ALLOW_DOTS}, as: :package_repositories_plugin_config
  get "admin/package_repositories/:id/:plugin/config/" => "admin/package_repositories#plugin_config_for_repo", constraints: {:plugin => ALLOW_DOTS}, as: :package_repositories_plugin_config_for_repo

  get "admin/pipelines/:pipeline_name/materials/pluggable_scm/show_existing" => "admin/materials/pluggable_scm#show_existing", constraints: {pipeline_name: PIPELINE_NAME_FORMAT}, as: :admin_pluggable_scm_show_existing
  post "admin/pipelines/:pipeline_name/materials/pluggable_scm/choose_existing" => "admin/materials/pluggable_scm#choose_existing", constraints: {pipeline_name: PIPELINE_NAME_FORMAT}, as: :admin_pluggable_scm_choose_existing
  get "admin/pipelines/:pipeline_name/materials/pluggable_scm/new/:plugin_id" => "admin/materials/pluggable_scm#new", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, plugin_id: ALLOW_DOTS}, as: :admin_pluggable_scm_new
  post "admin/pipelines/:pipeline_name/materials/pluggable_scm/:plugin_id" => "admin/materials/pluggable_scm#create", constraints: {pipeline_name: PIPELINE_NAME_FORMAT, plugin_id: ALLOW_DOTS}, as: :admin_pluggable_scm_create

server/webapp/WEB-INF/rails/app/controllers/admin/server_controller.rb
#
# Copyright 2019 ThoughtWorks, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

require 'pp'
require 'server_configuration_form'

class Admin::ServerController < AdminController
  include ApplicationHelper
  helper FlashMessagesHelper

  before_action :set_tab_name, :only => [:index, :update]

  def index
    set_defaults
    cruise_config = go_config_service.getConfigForEditing()
    @cruise_config_md5 = cruise_config.getMd5()
    @server_configuration_form = ServerConfigurationForm.from_server_config(cruise_config.server())
  end

  def test_email
    result = HttpLocalizedOperationResult.new
    server_configuration_form = ServerConfigurationForm.new(params[:server_configuration_form])
    if server_configuration_form.validate(result)
      server_config_service.sendTestMail(server_configuration_form.to_mail_host, result = HttpLocalizedOperationResult.new)
    end
    render :json => to_operation_result_json(result, 'Sent test email successfully.')
  end

  def update
    result = HttpLocalizedOperationResult.new
    @server_configuration_form = ServerConfigurationForm.new(params[:server_configuration_form])
    if @server_configuration_form.validate(result) &&
            update_server_config(@server_configuration_form.artifactsDir,
                                 @server_configuration_form.purgeStart,
                                 @server_configuration_form.purgeUpto,
                                 @server_configuration_form.jobTimeout,
                                 @server_configuration_form.should_allow_auto_login,
                                 @server_configuration_form.to_mail_host,
                                 @server_configuration_form.siteUrl,
                                 @server_configuration_form.secureSiteUrl,
                                 @server_configuration_form.commandRepositoryLocation,
                                 result)
      redirect_with_flash(result.message(), :action => :index, :class => 'success')
    else
      render_index_with_error(result)
    end
  end

  def validate
    @result = server_config_service.validateEmail(params[:email]) if params[:email]
    if params[:port]
      if number?(params[:port])
        @result = server_config_service.validatePort(Integer(params[:port]))
      else
        @result = HttpLocalizedOperationResult.new
        @result.invalid("Invalid port.")
      end
    end
    @result = server_config_service.validateHostName(params[:hostName]) if params[:hostName]
    render :json => to_operation_result_json(@result, 'Valid')
  end

  private
  def update_server_config(artifacts_dir, purgeStart, purgeUpto, jobTimeout, should_allow_auto_login, mail_host, site_url, secure_site_url,commandRepositoryLocation, result)
    server_config_service.updateServerConfig(mail_host, artifacts_dir, purgeStart, purgeUpto, jobTimeout, should_allow_auto_login, site_url, secure_site_url, commandRepositoryLocation, result, params[:cruise_config_md5])
    result.isSuccessful()
  end

  def render_index_with_error(result)
    session[:notice] = FlashMessageModel.new(result.message(), 'error')
    set_defaults
    @cruise_config_md5 = params[:cruise_config_md5]
    render :action => :index
  end

  def set_tab_name
    @tab_name = 'server_configuration'
  end

  def absolute_path_of_command_repo_dir
    system_environment.getCommandRepositoryRootLocation() + File::SEPARATOR
  end

  private
  def set_defaults
    @allow_user_to_turn_off_auto_login = user_service.canUserTurnOffAutoLogin()
    @command_repository_base_dir_location ||= absolute_path_of_command_repo_dir
  end
end

server/webapp/WEB-INF/rails/app/helpers/server_helper.rb
#
# Copyright 2019 ThoughtWorks, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

module ServerHelper
  def build_message(health_messages)
    messages = []

    if health_messages.errorCount() > 0
      messages << "#{health_messages.errorCount()} #{'error'.pluralize(health_messages.errorCount())}"
    end

    if health_messages.warningCount() > 0
      messages << "#{health_messages.warningCount()} #{'warning'.pluralize(health_messages.warningCount())}"
    end

    messages.join(' and ')
  end

end

server/webapp/WEB-INF/rails/app/views/admin/server/index.html.erb
<%- @view_title = "Administration" -%>
<script type="text/javascript">
    serverConfiguration = new ServerConfiguration("<%=validate_server_config_params_path%>");
</script>
<div id="server_configuration">
<%= form_for @server_configuration_form, :as => :server_configuration_form, :url => {:action => :update}, :html => {:method => 'post'} do |form| %>
    <%= config_md5_field %>
    <div id="server_management">
        <h2 class="legend">Server Management</h2>

        <div class="fieldset">
            <div class="form_item">
                <label for="server_configuration_form_site_url">Site URL</label>
                <%= form.text_field :siteUrl, :size => 30, :maxLength => 255 %>
                <div class="contextual_help has_go_tip_right" title="This entry will be used by Go Server to generate links for emails, feeds etc. Format: [protocol]://[host]:[port]. <a class='' href='<%= docs_url '/installation/configuring_server_details.html#configure-site-urls' %>' target='_blank'>More...</a>"></div>
                <span id="site_url_error_message"></span>
            </div>
            <div class="form_item">
                <label for="server_configuration_form_secure_site_url">Secure Site URL</label>
                <%= form.text_field :secureSiteUrl, :size => 30, :maxLength => 255 %>
                <div class="contextual_help has_go_tip_right" title="If you wish that your primary site URL be HTTP, but still want to have HTTPS endpoints for the features that require SSL, you can specify this attribute with a value of the base HTTPS URL. Format: https://[host]:[port].  <a class='' href='<%= docs_url '/installation/configuring_server_details.html#configure-site-urls' %>' target='_blank'>More...</a>"></div>
                <span id="secure_site_url_error_message"></span>
            </div>
        </div>
    </div>

    <div id="user_management">
        <h2 class="legend">User Management</h2>

        <div class="fieldset">

            <div class="form_item required">
                <div class="form_item checkbox_row">
                    <%- html_options = { } %>
                    <%- html_options = {:include_hidden => false, :disabled => true, :title => 'Cannot disable auto login with no admins enabled.'} unless @allow_user_to_turn_off_auto_login %>
                    <%= form.check_box :allow_auto_login, html_options, "true", "false" %>
                    <label class="inline" for="server_configuration_form_allow_auto_login">Allow users to login via plugin into GoCD, even if they haven't been explicitly added to GoCD.</label>
                </div>


                <div class="information">
                  <span>Support for LDAP and Password file authentication in GoCD core has been removed in favour of the bundled <%= link_to "LDAP", "https://github.com/gocd/gocd-ldap-authentication-plugin", target: "_blank" -%> and <%= link_to "Password File", "https://github.com/gocd/filebased-authentication-plugin", target: "_blank" -%> plugins respectively. Your existing LDAP and Password file configurations have been moved to <%= link_to "Authorization Configuration", '/go/admin/security/auth_configs' -%></span>
                </div>
            </div>
        </div>
    </div>
    <div id="mail_host">
        <div id="mail_host_config">
            <h2 class="legend">Email Notification</h2>

            <div class="fieldset">
                <div class="form_item required">
                    <div class="form_item">
                        <label for="server_configuration_form_hostName"><%= required_label_text('Hostname') -%></label>
                        <%= form.text_field :hostName, :size => 30, :maxLength => 64, :onblur => "serverConfiguration.validateHostName('server_configuration_form_hostName', 'hostname_error_message')" %>
                        <span id="hostname_error_message"></span>
                    </div>

                    <div class="form_item">

                        <label for="server_configuration_form_port"><%= required_label_text('Port') -%></label>
                        <%= form.text_field :port, :size => 30, :maxLength => 5, :onblur => "serverConfiguration.validatePort('server_configuration_form_port', 'port_error_message')" %>
                        <span id="port_error_message"></span>
                    </div>

                    <div class="form_item">

                        <label for="server_configuration_form_username">Username</label>
                        <%= form.text_field :username, :size => 30, :maxLength => 64 %>
                    </div>

                    <div class="form_item">
                        <label for="server_configuration_form_password">Password</label>
                        <%= form.password_field :password, :size => 30, :maxLength => 64, :disabled => true, :autocomplete => "off" %>
                        <span class="checkbox_row">
                                <%= form.check_box :password_changed, {}, "true", "false" %>
                            <label for="server_configuration_form_password_changed">Change Password</label>
                            </span>
                        <%= form.hidden_field :encrypted_password %>
                    </div>
                    <script type="text/javascript">
                        Util.on_load(function () {
                            var checkBox = jQuery("#server_configuration_form_password_changed");
                            var passwordField = jQuery("#server_configuration_form_password");
                            Util.bindPasswordField(checkBox, passwordField);
                        });
                    </script>
                    <div class="form_item checkbox_row">
                        <div class="checkbox_label_wrapper">
                            <%= form.check_box :tls, {}, "true", "false" %>
                            <label class="inline" for="server_configuration_form_tls">Use SMTPS</label>
                        </div>
                        <div class="contextual_help has_go_tip_right" title="This changes the protocol used to send the mail. It switches between SMTP and SMTPS. To enable STARTLS support, for providers such as GMail and Office 365, see <a class='' href='<%= docs_url '/configuration/admin_mailhost_info.html#starttls' %>' target='_blank'>this page in the documentation</a>."></div>
                    </div>

                    <div class="form_item">

                        <label for="server_configuration_form_from"><%= required_label_text('From') -%></label>
                        <%= form.text_field :from, :size => 30, :maxLength => 254, :onblur => "serverConfiguration.validateEmail('server_configuration_form_from', 'from_error_message')" %>
                        <span id="from_error_message"></span>
                    </div>

                    <div class="form_item">

                        <label for="server_configuration_form_adminMail"><%= required_label_text('Admin mail') -%></label>
                        <%= form.text_field :adminMail, :size => 30, :maxLength => 254, :onblur => "serverConfiguration.validateEmail('server_configuration_form_adminMail', 'admin_mail_error_message')" %>
                        <button type="button" class="submit tertiary" id="testNotification"
                                onclick="serverConfiguration.sendTestEmail(this, '<%= send_test_email_path %>', '<%= form_authenticity_token %>')">
                            <span>SEND TEST EMAIL</span>
                        </button>
                        <span id="admin_mail_error_message"></span>
                    </div>
                </div>
                <%= render :partial => 'shared/form_required_message.html', :locals => {:scope => {}} %>
            </div>
        </div>

    </div>
    <div id="pipeline_management">
        <h2 class="legend">Pipeline Management</h2>

        <div class="fieldset">
            <div class="form_item">
                <label for="artifacts_location">Artifacts Directory Location</label>
                <%= form.text_field :artifactsDir, :size => 30, :maxLength => 64, :id => "artifacts_location" %>
            </div>
            <div class="form_item">

                <label>Auto delete old artifacts:</label>

                <div class="checkbox_row">
                    <%= form.radio_button :purgeArtifacts, "Never", :id => "never_delete_artifacts" -%>
                    <label for="never_delete_artifacts">Never</label>
                </div>
                <div class="checkbox_row">
                    <%= form.radio_button :purgeArtifacts, "Size", :id => "select_artifact_purge_size" %>
                    <span class="checkbox_label">When available disk space is less than <%= form.text_field(:purgeStart, :size => 30, :maxLength => 64, :class => "small_text_field") %> GB, and keep deleting until <%= form.text_field(:purgeUpto, :size => 30, :maxLength => 64, :class => "small_text_field") %> GB free space is available</span>
                </div>
            </div>

            <div class="form_item" id="hung_job_timeout">
                <label>Default Job Timeout</label>

                <div class="checkbox_row">
                    <%= form.radio_button :timeoutType, "neverTimeout", :id => "hungjobs_neverTimeout" -%>
                    <%= label_tag 'hungjobs_neverTimeout', 'Never timeout' -%>
                </div>
                <div class="checkbox_row">
                    <%= form.radio_button :timeoutType, "overrideTimeout", :id => "hungjobs_overrideTimeout" -%>
                    <%= label_tag 'hungjobs_overrideTimeout', 'Cancel after' -%>
                    <%= form.text_field :jobTimeout, :size => 4, :maxLength => 64, :class => "small_text_field" -%>
                    <%= label_tag 'hungjobs_overrideTimeout', 'minute(s) of inactivity' -%>
                </div>
            </div>
        </div>
    </div>
    <div id="command_repository_management">
        <h2 class="legend">Command Repository Management</h2>

        <div class="fieldset">
            <div class="form_item" id="lookup-command-repo-location">
                <%= label_tag 'command_repo_location', 'Location' -%>

                <div class="path_textbox">
                    <%= label_tag 'command_repo_root_location', @command_repository_base_dir_location -%>
                    <%= form.text_field :commandRepositoryLocation -%>
                </div>

                <div class="contextual_help has_go_tip_right" title="Path to <a class='' href='<%= docs_url '/advanced_usage/command_repository.html' %>' target='_blank'>command repository</a> on Go Server. The location should be accessible to Go user."></div>
            </div>

            <div class="form_item" id="lookup-command-reload">
                <div class="button_row_with_help">
                    <button type="button" class="submit tertiary" id="reloadCommandRepoCache"
                            onclick="serverConfiguration.reloadCommandRepoCache('<%= admin_command_cache_reload_path -%>', 'command_repo_reload_result', '<%= form_authenticity_token %>')">
                        <span>Reload cache</span>
                    </button>
                    <div class="contextual_help has_go_tip_right" style='float:right;' title="Explicit reloading of the commands from the repository. Note: Changing the repository location above will automatically do this."></div>
                </div>
                <span id="command_repo_reload_result"></span>
            </div>
        </div>
    </div>

    <div class="form_buttons">
        <button type="submit" class="submit primary" id="submit_form"><span>SAVE</span></button>
        <button type="reset" class="submit" id="reset_form"><span>RESET</span></button>
    </div>
    <%= render :partial => 'shared/convert_tool_tips.html', :locals => {:scope => {}} %>
<% end %>
</div>